export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const GET_CURRENT_MENU_TERM = 'GET_CURRENT_MENU_TERM';
export const ADD_API_DATA = 'ADD_API_DATA';
export const GET_MOVIE_DETAILS = 'GET_MOVIE_DETAILS';
